defaults: &defaults
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  tmdb_key: <%= ENV['TMDB_KEY'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  amazon_affiliate: <%= ENV['AMAZON_AFFILIATE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
