development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: checkafilm_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: checkafilm_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost